MIN_REF_COVERAGE = -5.0
MAX_REF_SPREAD = 1.0
NULL_LOG2_coverInfo = -20.0

INSERT_SIZE = 250

IGNORE_GENE_NAMES = ("-", ".", "CGH")
OFFTARGET_NAME = "offTarget"
OFFTARGET_ALIASES = (OFFTARGET_NAME, "Background")
